{% set name = "pytest-describe" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5cbaa31169f0060348ad5ca0191027e5f1f41f3f27fdeef208365e09c55eb9a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest >=4.0.0

test:
  requires:
    - pytest-cov
    - pip
  source_files:
    - test
  imports:
    - pytest_describe
  commands:
    - python -m pip check
    - pytest --cov pytest_describe

about:
  home: https://github.com/ropez/pytest-describe
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Describe-style plugin for py.test
  description: |
    pytest-describe is a plugin for pytest that allows tests to be written in arbitrary
    nested describe-blocks, similar to RSpec (Ruby) and Jasmine (JavaScript).

extra:
  recipe-maintainers:
    - bollwyvl
